FROM ubuntu:16.04

RUN apt update \ 
  && apt install vim --assume-yes \
  && apt install python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev -y --assume-yes \
  && apt install memcached -y --assume-yes

WORKDIR /usr/bin

RUN ln -s pip3 pip

RUN ln -s python3 python


